---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Blog
- type: directory
  path: content/english/blog
  label: English Blog
  create: all
  match: "**/*"
  templates:
  - test-template
- type: directory
  path: content/french/blog
  label: French Blog
  create: all
  match: "**/*"
  templates:
  - test-template
- type: heading
  label: Pages
- type: directory
  path: content/french
  label: French
  create: all
  match: "*.html"
  new_doc_ext: html
  templates:
  - page
- type: directory
  path: content/english
  label: English
  create: all
  match: "*.html"
  new_doc_ext: html
  templates:
  - page
- type: heading
  label: Config
- type: document
  path: config.toml
  label: Hugo config
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.62.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.59.1
